add stat reporting

diff --git a/.github/workflows/webhook-test.yml b/.github/workflows/webhook-test.yml
--- a/.github/workflows/webhook-test.yml
+++ b/.github/workflows/webhook-test.yml
@@ -8,21 +8,25 @@ jobs:
    runs-on: ubuntu-latest
    outputs:
      added_instructions: ${{ steps.generate-manifest.outputs.added_instructions }}
+     updated_instructions: ${{ steps.generate-manifest.outputs.updated_instructions }}
      total_instructions: ${{ steps.generate-manifest.outputs.total_instructions }}
      included_messages: ${{ steps.generate-manifest.outputs.included_messages }}
      skipped_messages: ${{ steps.generate-manifest.outputs.skipped_messages }}
      failure_reason: ${{ steps.generate-manifest.outputs.failure_reason }}
+     notices: ${{ steps.generate-manifest.outputs.notices }}
    steps:
      - name: Simulate Return
        id: generate-manifest
+       #  run: |
+       #    echo "failure_reason=Mama a girl behind you" >> "$GITHUB_OUTPUT"
+       #    exit 1
        run: |
-         echo "failure_reason=Mama a girl behind you" >> "$GITHUB_OUTPUT"
-         exit 1
-       # run: |
-       #   echo "added_instructions=1" >> "$GITHUB_OUTPUT"
-       #   echo "total_instructions=5" >> "$GITHUB_OUTPUT"
-       #   echo "included_messages=3" >> "$GITHUB_OUTPUT"
-       #   echo "skipped_messages=2" >> "$GITHUB_OUTPUT"
+         echo "added_instructions=1" >> "$GITHUB_OUTPUT"
+         echo "updated_instructions=4" >> "$GITHUB_OUTPUT"
+         echo "total_instructions=5" >> "$GITHUB_OUTPUT"
+         echo "included_messages=3" >> "$GITHUB_OUTPUT"
+         echo "skipped_messages=2" >> "$GITHUB_OUTPUT"
+         echo "notices=mama a girl behind u 💜" >> "$GITHUB_OUTPUT"
 
  send-discord-message:
    needs: simulate-task
@@ -33,7 +37,7 @@ jobs:
        id: generate-json
        run: |
          if [[ "${{ needs.simulate-task.result }}" == "success" ]]; then
-           echo 'embed_json=[{"author":{"name":"Generate manifest.json","url":"https://github.com/ryan-roche/gophermaps-data/actions/workflows/manifest-generator.yml","icon_url":"https://github.com/github.png"},"title":"Updated Manifest","url":"${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}","color":4029719,"fields":[{"name":"📜  Instructions","value":"- 📄  Added ${{ needs.simulate-task.outputs.added_instructions }}\n - 🗃️  Total: ${{ needs.simulate-task.outputs.total_instructions }}"},{"name":"📣  Server Messages","value":"- 📥  ${{ needs.simulate-task.outputs.included_messages }} included\n - ⏭️  ${{ needs.simulate-task.outputs.skipped_messages }} skipped"}],"thumbnail":{"url":"https://github.com/actions-user.png"}}]' >> $GITHUB_OUTPUT
+           echo 'embed_json=[{"author":{"name":"Generate manifest.json","url":"https://github.com/ryan-roche/gophermaps-data/actions/workflows/manifest-generator.yml","icon_url":"https://github.com/github.png"},"title":"Updated Manifest","url":"${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}","description":${{ needs.simulate-task.outputs.notices }},"color":4029719,"fields":[{"name":"📜  Instructions","value":"- 📄  Added ${{ needs.simulate-task.outputs.added_instructions }}\n - 🗃️  Total: ${{ needs.simulate-task.outputs.total_instructions }}"},{"name":"📣  Server Messages","value":"- 📥  ${{ needs.simulate-task.outputs.included_messages }} included\n - ⏭️  ${{ needs.simulate-task.outputs.skipped_messages }} skipped"}],"thumbnail":{"url":"https://github.com/actions-user.png"}}]' >> $GITHUB_OUTPUT
          else
            echo 'embed_json=[{"author":{"name":"Generate manifest.json","url":"https://github.com/ryan-roche/gophermaps-data/actions/workflows/manifest-generator.yml","icon_url":"https://github.com/github.png"},"title":"Failed to generate Manifest","url":"${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}","description":${{ needs.simulate-task.outputs.failure_reason }},"color":12845056,"thumbnail":{"url":"https://github.com/actions-user.png"}}]' >> $GITHUB_OUTPUT
          fi
